drop table if exists infection_report CASCADE;

drop table if exists items_points CASCADE;

drop table if exists status CASCADE;

drop table if exists survivor CASCADE;

create table infection_report (
   id integer generated by default as identity,
    id_snitch integer,
    id_status integer not null,
    primary key (id)
);

create table items_points (
   description varchar(255) not null,
    points integer,
    primary key (description)
);

create table status (
   id integer generated by default as identity,
    infected boolean,
    primary key (id)
);

create table survivor (
   id integer generated by default as identity,
    age integer not null,
    gender varchar(50) not null,
    inventory varchar(255) not null,
    last_location varchar(100) not null,
    name varchar(100) not null,
    id_status integer,
    primary key (id)
);

alter table infection_report
   add constraint fk_snitch
   foreign key (id_snitch)
   references survivor;

alter table infection_report
   add constraint fk_status_report
   foreign key (id_status)
   references status;

alter table survivor
   add constraint fk_status_survivor
   foreign key (id_status)
   references status;

